name: nubank_telainicial
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.8
  eva_icons_flutter: ^3.0.0 # Biblioteca adicionada para ícones estilizados

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true # Garante que os ícones do Material Design funcionem
  assets:
    - assets/usuario.png
    # Diretório para ícones customizados em PNG ou SVG
